import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, "..");
const srcRoot = join(web, "..", "..", "..", "Projet-landing-src");
const srcAssets = join(srcRoot, "assets");
const publicDir = join(web, "public", "landing");
const outDir = join(web, "components", "landing");

mkdirSync(publicDir, { recursive: true });
mkdirSync(outDir, { recursive: true });

const IMAGES = [
  "logo-dark.png",
  "logo-white.png",
  "fluid-full.webp",
  "fluid-full.avif",
  "spectrum.webp",
  "spectrum.avif",
  "founder-andrei-loh.webp",
  "founder-le-mai-thi.webp",
  "favicon.ico",
  "favicon-32.png",
  "favicon.svg",
  "apple-touch-icon.png",
  "og-cover.jpg",
];

for (const name of IMAGES) {
  copyFileSync(join(srcAssets, name), join(publicDir, name));
}

function rewriteHtml(html) {
  return html
    .replaceAll("href=\"challenges.html\"", "href=\"/challenges\"")
    .replaceAll("href=\"about.html\"", "href=\"/about\"")
    .replaceAll("href=\"faq.html\"", "href=\"/faq\"")
    .replaceAll("href=\"index.html#", "href=\"/#")
    .replaceAll("href=\"index.html\"", "href=\"/\"")
    .replaceAll("href=\"signup.html?role=business\"", "href=\"/company/signup\"")
    .replaceAll("href=\"signup.html?role=builder\"", "href=\"/signup\"")
    .replaceAll("href=\"signup.html\"", "href=\"/signup\"")
    .replaceAll("href=\"login.html\"", "href=\"/signin\"")
    .replaceAll("href=\"dashboard.html?view=company\"", "href=\"/company\"")
    .replaceAll("href=\"dashboard.html?view=student\"", "href=\"/home\"")
    .replaceAll("href=\"dashboard.html\"", "href=\"/home\"")
    .replaceAll("src=\"assets/", "src=\"/landing/");
}

function extractMain(filename) {
  const raw = readFileSync(join(srcRoot, filename), "utf8");
  const start = raw.indexOf("<main");
  const end = raw.indexOf("</main>") + "</main>".length;
  if (start < 0 || end < "</main>".length) {
    throw new Error(`Could not find <main> in ${filename}`);
  }
  return rewriteHtml(raw.slice(start, end));
}

function toTsModule(name, html) {
  return `/* Generated by scripts/port-landing.mjs — do not edit by hand. */\nexport const ${name} = ${JSON.stringify(html)};\n`;
}

writeFileSync(join(outDir, "home-markup.ts"), toTsModule("HOME_MAIN", extractMain("index.html")));
writeFileSync(join(outDir, "about-markup.ts"), toTsModule("ABOUT_MAIN", extractMain("about.html")));
writeFileSync(join(outDir, "faq-markup.ts"), toTsModule("FAQ_MAIN", extractMain("faq.html")));

function scopeCss(css) {
  let scoped = css
    .replace(/:root\s*\{/g, ":scope{")
    .replace(/html\[data-audience/g, ":scope[data-audience")
    .replace(/html\.no-js/g, ":scope.no-js")
    .replace(/^html\{/gm, ":scope{")
    .replace(/^body\{/gm, ":scope{");

  return `/* Generated by scripts/port-landing.mjs from the marketing repo. */
@scope (.landing-root) {
${scoped}
}
`;
}

writeFileSync(join(publicDir, "landing.css"), scopeCss(readFileSync(join(srcAssets, "landing.css"), "utf8")));
writeFileSync(join(publicDir, "pages.css"), scopeCss(readFileSync(join(srcAssets, "pages.css"), "utf8")));

let js = readFileSync(join(srcAssets, "landing.js"), "utf8");
js = js
  .replace(
    "var reducedMotion = window.matchMedia &&",
    `var landingRoot = document.querySelector(".landing-root") || document.documentElement;
  var reducedMotion = window.matchMedia &&`,
  )
  .replaceAll(
    'document.documentElement.getAttribute("data-audience")',
    'landingRoot.getAttribute("data-audience")',
  )
  .replaceAll(
    'document.documentElement.setAttribute("data-audience", mode)',
    'landingRoot.setAttribute("data-audience", mode)',
  )
  .replace(
    ".observe(document.documentElement, { attributes: true, attributeFilter: [\"data-audience\"] });",
    ".observe(landingRoot, { attributes: true, attributeFilter: [\"data-audience\"] });",
  )
  .replaceAll(
    'document.documentElement.style.setProperty("--nav-h"',
    'landingRoot.style.setProperty("--nav-h"',
  )
  .replaceAll(
    'document.documentElement.style.setProperty("--footer-h"',
    'landingRoot.style.setProperty("--footer-h"',
  )
  .replace(
    /try \{ loggedIn = localStorage\.getItem\("projet:loggedIn"\) === "1"; \} catch \(e\) \{ \/\* private mode \*\/ \}\s*if \(loggedIn\) return;[\s\S]*?link\.setAttribute\("href", "signup\.html\?role=" \+ \(business \? "business" : "builder"\)\);/,
    `loggedIn = landingRoot.getAttribute("data-signed-in") === "1";
    var business = landingRoot.getAttribute("data-audience") === "business";
    if (loggedIn) {
      link.textContent = "Open dashboard";
      link.setAttribute("href", business ? "/company" : "/home");
      return;
    }
    link.textContent = business ? "Post a challenge" : "Join Us";
    link.setAttribute("href", business ? "/company/signup" : "/signup");`,
  )
  .replace(
    /document\.querySelectorAll\('a\[href\^="signup\.html"\]'\)\.forEach\(function \(a\) \{[\s\S]*?a\.setAttribute\("href", "signup\.html\?role=" \+ \(mode === "business" \? "business" : "builder"\)\);\s*\}\);/,
    `document.querySelectorAll('a[href="/signup"], a[href="/company/signup"]').forEach(function (a) {
        if (a.closest("[data-mode-copy]")) return;
        a.setAttribute("href", mode === "business" ? "/company/signup" : "/signup");
      });
      document.querySelectorAll('a[href="/signin"], a[href="/company/signin"]').forEach(function (a) {
        if (a.closest("[data-mode-copy]")) return;
        a.setAttribute("href", mode === "business" ? "/company/signin" : "/signin");
      });`,
  )
  .replace(
    'a[href^="dashboard.html"]',
    "a[data-dash-link]",
  )
  .replace(
    'a.setAttribute("href", "dashboard.html?view=" + view);',
    `a.setAttribute("href", landingRoot.getAttribute("data-signed-in") === "1"
          ? (mode === "business" ? "/company" : "/home")
          : (mode === "business" ? "/company/signin" : "/signin"));`,
  )
  .replace(
    /var STORE = "projet:loggedIn";[\s\S]*?if \(loggedIn\) final\.hidden = true;/,
    `if (landingRoot.getAttribute("data-signed-in") === "1") final.hidden = true;`,
  );

if (!js.includes("var landingRoot = document.querySelector")) {
  throw new Error("Failed to inject landingRoot into landing.js");
}

const openMatch = js.match(/\(function\s*\(\)\s*\{\s*"use strict";/);
const close = js.lastIndexOf("})();");
if (!openMatch || close < 0) {
  throw new Error("Could not unwrap landing.js IIFE");
}
const body = js.slice(openMatch.index + openMatch[0].length, close);

const runtime = `/* Generated by scripts/port-landing.mjs from the marketing repo. */
export function mountLanding() {
  const cleanups = [];
  let alive = true;
  cleanups.push(() => {
    alive = false;
  });

  const OrigIO = window.IntersectionObserver;
  window.IntersectionObserver = function (...args) {
    const io = new OrigIO(...args);
    cleanups.push(() => io.disconnect());
    return io;
  };

  const OrigMO = window.MutationObserver;
  window.MutationObserver = function (...args) {
    const mo = new OrigMO(...args);
    cleanups.push(() => mo.disconnect());
    return mo;
  };

  const addWin = window.addEventListener.bind(window);
  const removeWin = window.removeEventListener.bind(window);
  window.addEventListener = function (type, fn, opts) {
    addWin(type, fn, opts);
    cleanups.push(() => removeWin(type, fn, opts));
  };

  const addDoc = document.addEventListener.bind(document);
  const removeDoc = document.removeEventListener.bind(document);
  document.addEventListener = function (type, fn, opts) {
    addDoc(type, fn, opts);
    cleanups.push(() => removeDoc(type, fn, opts));
  };

  const origInterval = window.setInterval.bind(window);
  window.setInterval = function (...args) {
    const id = origInterval(...args);
    cleanups.push(() => clearInterval(id));
    return id;
  };

  const origRaf = window.requestAnimationFrame.bind(window);
  window.requestAnimationFrame = function (cb) {
    return origRaf((t) => {
      if (!alive) return;
      cb(t);
    });
  };

  try {
    (function () {
      "use strict";
${body}
    })();
  } finally {
    window.IntersectionObserver = OrigIO;
    window.MutationObserver = OrigMO;
    window.addEventListener = addWin;
    document.addEventListener = addDoc;
    window.setInterval = origInterval;
    window.requestAnimationFrame = origRaf;
  }

  return function unmountLanding() {
    for (const fn of cleanups) {
      try { fn(); } catch { /* ignore */ }
    }
  };
}
`;

writeFileSync(join(outDir, "runtime.ts"), `// @ts-nocheck\n${runtime}`);

console.log("ported landing assets");
