"""replace magic link with password auth

Revision ID: 0e3cc3eb0f20
Revises: 6839fab25450
Create Date: 2026-09-13 11:48:45.337771
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import projet.models.base

revision = '0e3cc3eb0f20'
down_revision = '6839fab25450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_action_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('platform', 'company_user', 'participant', name='actortype', native_enum=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('set_password', 'reset_password', name='accountactionpurpose', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('redirect_path', sa.String(length=500), nullable=True),
    sa.Column('expires_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', projet.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_action_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_account_action_token_token_hash'))
    )
    with op.batch_alter_table('account_action_token', schema=None) as batch_op:
        batch_op.create_index('ix_account_action_token_subject', ['actor_type', 'subject_id'], unique=False)

    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magic_link_token_subject'))

    op.drop_table('magic_link_token')
    with op.batch_alter_table('company_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    with op.batch_alter_table('platform_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('company_user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('magic_link_token',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('redirect_path', sa.TEXT(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('consumed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('subject_id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_link_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_magic_link_token_token_hash'))
    )
    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magic_link_token_subject'), ['actor_type', 'subject_id'], unique=False)

    with op.batch_alter_table('account_action_token', schema=None) as batch_op:
        batch_op.drop_index('ix_account_action_token_subject')

    op.drop_table('account_action_token')
    # ### end Alembic commands ###
