"""portfolio project entries and public profile fields

Revision ID: 552df2a6b0f2
Revises: a1b2c3d4e5f6
Create Date: 2026-09-18 11:07:15.371172
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import projet.models.base

revision = '552df2a6b0f2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('programme', 'hackathon', 'internship', 'freelance', 'competition', 'independent', name='projectkind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('organisation_name', sa.String(length=300), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('contribution', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('artifact_visibility', sa.Enum('private', 'link_only', 'public', name='artifactvisibility', native_enum=False), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_project_entry_participant_id_participant'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_project_entry_person_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_entry')),
    sa.UniqueConstraint('participant_id', name='uq_project_entry_participant')
    )
    op.create_table('project_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_entry_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('github', 'demo', 'video', 'deck', 'doc', 'brief', name='projectlinkkind', native_enum=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_entry_id'], ['project_entry.id'], name=op.f('fk_project_link_project_entry_id_project_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_link'))
    )
    op.create_table('project_skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_entry_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_entry_id'], ['project_entry.id'], name=op.f('fk_project_skill_project_entry_id_project_entry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_project_skill_skill_id_skill')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_skill')),
    sa.UniqueConstraint('project_entry_id', 'skill_id', name=op.f('uq_project_skill_project_entry_id'))
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=160), nullable=True))
        # NOT NULL onto a populated table needs a default to backfill with.
        # False is the right backfill as well as the right default: nobody
        # consented to a public profile before the column existed.
        # SQLite batch-recreates the table as the *final* schema of this
        # block, so dropping the default in the same batch would copy rows
        # into a NOT NULL column with no default and fail.
        batch_op.add_column(
            sa.Column('public', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('public', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('public')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')
        batch_op.drop_column('headline')

    op.drop_table('project_skill')
    op.drop_table('project_link')
    op.drop_table('project_entry')
    # ### end Alembic commands ###
