"""M1: problem statement drafts and programme overrides

Revision ID: 6839fab25450
Revises: abe37edca73b
Create Date: 2026-09-12 20:24:24.831871
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import projet.models.base

revision = '6839fab25450'
down_revision = 'abe37edca73b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_statement_draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('outputs', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('grounding', sa.Text(), nullable=True),
    sa.Column('based_on_live_listing', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('accepted_at', projet.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_problem_statement_draft_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_statement_draft'))
    )
    with op.batch_alter_table('programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_statement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deliverable_spec', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requires_confidentiality_ack', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programme', schema=None) as batch_op:
        batch_op.drop_column('requires_confidentiality_ack')
        batch_op.drop_column('deliverable_spec')
        batch_op.drop_column('problem_statement')

    op.drop_table('problem_statement_draft')
    # ### end Alembic commands ###
