"""initial schema

Revision ID: 804c91b848d2
Revises: 
Create Date: 2026-09-12 19:36:29.868854
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import projet.models.base


revision = '804c91b848d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('detail', projet.models.base.JSONEncoded(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('tier', sa.Enum('sme', 'midmarket', 'enterprise', name='companytier', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('slug', name=op.f('uq_company_slug'))
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('slug', name=op.f('uq_event_slug'))
    )
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('google_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('organisation', sa.String(length=300), nullable=True),
    sa.Column('org_type', sa.Enum('school', 'company', 'association', name='orgtype', native_enum=False), nullable=True),
    sa.Column('year_course', sa.String(length=300), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('handle', name=op.f('uq_person_handle'))
    )
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('aliases', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_role_slug'))
    )
    op.create_table('skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('hard', 'soft', name='skilltype', native_enum=False), nullable=False),
    sa.Column('aliases', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('status', sa.Enum('canonical', 'pending_review', name='skillstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill')),
    sa.UniqueConstraint('name', name=op.f('uq_skill_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_skill_slug'))
    )
    op.create_table('company_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'rep', 'viewer', name='companyuserrole', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'disabled', name='companyuserstatus', native_enum=False), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_user_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['company_user.id'], name=op.f('fk_company_user_invited_by_company_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_user')),
    sa.UniqueConstraint('company_id', 'email', name=op.f('uq_company_user_company_id'))
    )
    op.create_table('programme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('brief_url', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('delivery_mode', sa.Enum('online', 'in_person', 'hybrid', name='deliverymode', native_enum=False), nullable=False),
    sa.Column('team_size_max', sa.Integer(), nullable=False),
    sa.Column('applications_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applications_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'selecting', 'confirmed', 'running', 'submitted', 'judging', 'complete', name='programmestatus', native_enum=False), nullable=False),
    sa.Column('deadline_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('team_size_max >= 1', name=op.f('ck_programme_team_size_max_positive')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_programme_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_programme_event_id_event'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_programme_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programme')),
    sa.UniqueConstraint('company_id', 'slug', name=op.f('uq_programme_company_id'))
    )
    op.create_table('role_template',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('default_deliverable', sa.Text(), nullable=False),
    sa.Column('public_sources', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('student_tools', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('asks_easy', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('asks_moderate', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('asks_hard', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('rubric_slot2_name', sa.String(length=160), nullable=False),
    sa.Column('rubric_slot2_anchor_5', sa.Text(), nullable=False),
    sa.Column('rubric_slot2_anchor_3', sa.Text(), nullable=False),
    sa.Column('rubric_slot2_anchor_1', sa.Text(), nullable=False),
    sa.Column('rubric_slot3_name', sa.String(length=160), nullable=False),
    sa.Column('rubric_slot3_anchor_5', sa.Text(), nullable=False),
    sa.Column('rubric_slot3_anchor_3', sa.Text(), nullable=False),
    sa.Column('rubric_slot3_anchor_1', sa.Text(), nullable=False),
    sa.Column('ranked_hard_skills', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('ranked_soft_skills', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('delivery_risk_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_template_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_role_template'))
    )
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('cv_url', sa.Text(), nullable=True),
    sa.Column('writeup', sa.Text(), nullable=True),
    sa.Column('consent_share_company', sa.Boolean(), nullable=False),
    sa.Column('consent_recording', sa.Boolean(), nullable=False),
    sa.Column('consent_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_relevance', sa.Integer(), nullable=True),
    sa.Column('score_specificity', sa.Integer(), nullable=True),
    sa.Column('score_capability', sa.Integer(), nullable=True),
    sa.Column('score_followthrough', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'screened', 'offered', 'waitlisted', 'rejected', 'accepted', 'declined', 'expired', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('offer_token', sa.String(length=128), nullable=True),
    sa.Column('offer_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_application_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_application_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application')),
    sa.UniqueConstraint('offer_token', name=op.f('uq_application_offer_token')),
    sa.UniqueConstraint('programme_id', 'person_id', name=op.f('uq_application_programme_id'))
    )
    op.create_table('credential',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('completion', 'top_performer', name='credentialtype', native_enum=False), nullable=False),
    sa.Column('verify_code', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_credential_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_credential_programme_id_programme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential')),
    sa.UniqueConstraint('person_id', 'programme_id', 'type', name=op.f('uq_credential_person_id')),
    sa.UniqueConstraint('verify_code', name=op.f('uq_credential_verify_code'))
    )
    op.create_table('data_pack_resource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('url_or_storage_key', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Enum('public', 'company_supplied', name='provenance', native_enum=False), nullable=False),
    sa.Column('licence', sa.String(length=200), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'failed', name='verificationstatus', native_enum=False), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_status', sa.String(length=40), nullable=True),
    sa.Column('notes', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_data_pack_resource_programme_id_programme'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_data_pack_resource_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['company_user.id'], name=op.f('fk_data_pack_resource_uploaded_by_company_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_pack_resource'))
    )
    op.create_table('judging_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_or_meet_link', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=300), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_judging_session_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_judging_session'))
    )
    op.create_table('magic_link_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('redirect_path', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['company_user.id'], name=op.f('fk_magic_link_token_company_user_id_company_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magic_link_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_magic_link_token_token_hash'))
    )
    op.create_table('profile_skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('attested_by_name', sa.String(length=200), nullable=True),
    sa.Column('attested_by_title', sa.String(length=200), nullable=True),
    sa.Column('attested_by_company', sa.String(length=200), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_profile_skill_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_profile_skill_programme_id_programme')),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_profile_skill_skill_id_skill')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_skill')),
    sa.UniqueConstraint('person_id', 'programme_id', 'skill_id', name=op.f('uq_profile_skill_person_id'))
    )
    op.create_table('programme_assignment',
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('company_user_id', sa.Uuid(), nullable=False),
    sa.Column('can_score', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_user_id'], ['company_user.id'], name=op.f('fk_programme_assignment_company_user_id_company_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_programme_assignment_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programme_id', 'company_user_id', name=op.f('pk_programme_assignment'))
    )
    op.create_table('rubric_criterion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('anchor_5', sa.Text(), nullable=True),
    sa.Column('anchor_3', sa.Text(), nullable=True),
    sa.Column('anchor_1', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('slot between 1 and 4', name=op.f('ck_rubric_criterion_slot_range')),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_rubric_criterion_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rubric_criterion')),
    sa.UniqueConstraint('programme_id', 'slot', name=op.f('uq_rubric_criterion_programme_id'))
    )
    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_team_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.create_table('thread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('announcement', 'resource', 'question_challenge', 'question_logistics', 'direct', name='threadtype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('author_role', sa.Enum('admin', 'rep', 'participant', name='authorrole', native_enum=False), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'answered', name='threadstatus', native_enum=False), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('requires_ack', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['thread.id'], name=op.f('fk_thread_merged_into_id_thread'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_thread_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread'))
    )
    op.create_table('participant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('programme_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=120), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.Column('run_order', sa.Integer(), nullable=True),
    sa.Column('judging_session_id', sa.Uuid(), nullable=True),
    sa.Column('attended_kickoff', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'active', 'submitted', 'no_submission', 'pitched', 'closed', name='participantstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_participant_application_id_application')),
    sa.ForeignKeyConstraint(['judging_session_id'], ['judging_session.id'], name=op.f('fk_participant_judging_session_id_judging_session'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_participant_person_id_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], name=op.f('fk_participant_programme_id_programme'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant')),
    sa.UniqueConstraint('programme_id', 'person_id', name=op.f('uq_participant_programme_id'))
    )
    op.create_table('post',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('author_role', sa.Enum('admin', 'rep', 'participant', name='authorrole', native_enum=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_post_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_table('score',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('scorer_id', sa.Uuid(), nullable=False),
    sa.Column('scorer_type', sa.Enum('rep', 'judge', 'mentor', name='scorertype', native_enum=False), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scorer_id'], ['company_user.id'], name=op.f('fk_score_scorer_id_company_user')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_score_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score')),
    sa.UniqueConstraint('team_id', 'scorer_id', name=op.f('uq_score_team_id'))
    )
    op.create_table('submission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'complete', 'locked', name='submissionstatus', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_submission_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission')),
    sa.UniqueConstraint('team_id', name=op.f('uq_submission_team_id'))
    )
    op.create_table('thread_member',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_role', sa.Enum('admin', 'rep', 'participant', name='authorrole', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_thread_member_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'user_id', name=op.f('pk_thread_member'))
    )
    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_attachment_post_id_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    op.create_table('criterion_score',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value between 1 and 5', name=op.f('ck_criterion_score_value_range')),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criterion.id'], name=op.f('fk_criterion_score_criterion_id_rubric_criterion')),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], name=op.f('fk_criterion_score_score_id_score'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id', 'criterion_id', name=op.f('pk_criterion_score')),
    sa.UniqueConstraint('score_id', 'criterion_id', name=op.f('uq_criterion_score_score_id'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.Enum('participant', 'application', 'company_user', 'programme', 'submission_link', name='outboxsubjecttype', native_enum=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('effect_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=False),
    sa.Column('payload', projet.models.base.JSONEncoded(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', projet.models.base.JSONEncoded(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_outbox_participant_id_participant'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbox_idempotency_key'))
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_due', ['status', 'next_attempt_at'], unique=False)
        batch_op.create_index('ix_outbox_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('score_member',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('would_refer', sa.Enum('yes', 'maybe', 'no', name='referralintent', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_score_member_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], name=op.f('fk_score_member_score_id_score'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id', 'participant_id', name=op.f('pk_score_member'))
    )
    op.create_table('score_skill_tag',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_score_skill_tag_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], name=op.f('fk_score_skill_tag_score_id_score'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_score_skill_tag_skill_id_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('score_id', 'participant_id', 'skill_id', name=op.f('pk_score_skill_tag'))
    )
    op.create_table('submission_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.Enum('artifact', 'memo', 'extra', name='submissionslot', native_enum=False), nullable=False),
    sa.Column('drive_url', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.String(length=200), nullable=True),
    sa.Column('detected_filename', sa.String(length=400), nullable=True),
    sa.Column('detected_mime', sa.String(length=200), nullable=True),
    sa.Column('access_status', sa.Enum('ok', 'denied', 'not_found', 'unchecked', name='accessstatus', native_enum=False), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_key', sa.Text(), nullable=True),
    sa.Column('snapshot_mime', sa.String(length=200), nullable=True),
    sa.Column('snapshot_bytes', sa.Integer(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_status', sa.Enum('pending', 'ok', 'failed', name='snapshotstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name=op.f('fk_submission_link_submission_id_submission'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_link')),
    sa.UniqueConstraint('submission_id', 'slot', name=op.f('uq_submission_link_submission_id'))
    )
    op.create_table('team_member',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_team_member_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_member_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'participant_id', name=op.f('pk_team_member'))
    )
    op.create_table('testimonial',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('author_company_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_company_user_id'], ['company_user.id'], name=op.f('fk_testimonial_author_company_user_id_company_user')),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_testimonial_participant_id_participant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonial'))
    )
    op.create_table('thread_read',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_thread_read_participant_id_participant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_thread_read_thread_id_thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'participant_id', name=op.f('pk_thread_read'))
    )
    # ### end Alembic commands ###


    # Alembic does not autogenerate expression indexes. This one is load-bearing:
    # it is what makes one human resolve to one Person across cohorts, so their
    # profile compounds instead of starting over.
    op.create_index(
        "ix_person_contact_email_lower",
        "person",
        [sa.text("lower(contact_email)")],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index("ix_person_contact_email_lower", table_name="person")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_read')
    op.drop_table('testimonial')
    op.drop_table('team_member')
    op.drop_table('submission_link')
    op.drop_table('score_skill_tag')
    op.drop_table('score_member')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_subject')
        batch_op.drop_index('ix_outbox_due')

    op.drop_table('outbox')
    op.drop_table('criterion_score')
    op.drop_table('attachment')
    op.drop_table('thread_member')
    op.drop_table('submission')
    op.drop_table('score')
    op.drop_table('post')
    op.drop_table('participant')
    op.drop_table('thread')
    op.drop_table('team')
    op.drop_table('rubric_criterion')
    op.drop_table('programme_assignment')
    op.drop_table('profile_skill')
    op.drop_table('magic_link_token')
    op.drop_table('judging_session')
    op.drop_table('data_pack_resource')
    op.drop_table('credential')
    op.drop_table('application')
    op.drop_table('role_template')
    op.drop_table('programme')
    op.drop_table('company_user')
    op.drop_table('skill')
    op.drop_table('role')
    op.drop_table('person')
    op.drop_table('event')
    op.drop_table('company')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_subject')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
