"""auth: platform users, polymorphic magic links, sessions

Revision ID: abe37edca73b
Revises: 804c91b848d2
Create Date: 2026-09-12 20:15:56.993071
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import projet.models.base

revision = 'abe37edca73b'
down_revision = '804c91b848d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('platform', 'company_user', 'participant', name='actortype', native_enum=False), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('expires_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', projet.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_session_token_hash'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index('ix_auth_session_subject', ['actor_type', 'subject_id'], unique=False)

    op.create_table('platform_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='platformrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', projet.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_user')),
    sa.UniqueConstraint('email', name=op.f('uq_platform_user_email'))
    )
    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_type', sa.Enum('platform', 'company_user', 'participant', name='actortype', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('subject_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=320), nullable=False))
        batch_op.create_index('ix_magic_link_token_subject', ['actor_type', 'subject_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_magic_link_token_company_user_id_company_user'), type_='foreignkey')
        batch_op.drop_column('company_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_link_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_user_id', sa.CHAR(length=32), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_magic_link_token_company_user_id_company_user'), 'company_user', ['company_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_magic_link_token_subject')
        batch_op.drop_column('email')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('actor_type')

    op.drop_table('platform_user')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_session_subject')

    op.drop_table('auth_session')
    # ### end Alembic commands ###
