"""capability rollup for skills

Revision ID: bf80f1a3cef9
Revises: 0e3cc3eb0f20
Create Date: 2026-09-13 13:36:14.645888
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import projet.models.base

revision = 'bf80f1a3cef9'
down_revision = '0e3cc3eb0f20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', projet.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability')),
    sa.UniqueConstraint('name', name=op.f('uq_capability_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_capability_slug'))
    )
    op.create_table('skill_capability',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capability.id'], name=op.f('fk_skill_capability_capability_id_capability'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_skill_capability_skill_id_skill'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'capability_id', name=op.f('pk_skill_capability'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_capability')
    op.drop_table('capability')
    # ### end Alembic commands ###
